EVALUATE_PROMPT = (
    "RAG 시스템의 답변을 아래 3가지 기준으로 평가하세요.\n\n"
    "1. faithfulness (충실도)\n"
    "   - 답변이 제공된 컨텍스트에만 근거하는가?\n"
    "   - 컨텍스트에 없는 내용을 지어내지 않았는가?\n\n"
    "2. answer_relevance (답변 관련성)\n"
    "   - 답변이 질문에 직접적으로 답하는가?\n"
    "   - 핵심을 빠뜨리지 않았는가?\n\n"
    "3. context_relevance (검색 품질)\n"
    "   - 검색된 청크들이 질문에 답하기에 충분한 정보를 담고 있는가?\n"
    "   - 무관한 청크가 포함되지 않았는가?\n\n"
    "각 항목을 1~5점으로 평가하세요. (5: 매우 좋음, 1: 매우 나쁨)\n\n"
    "반드시 아래 JSON만 출력하세요:\n"
    "{\n"
    "  \"faithfulness\":      {\"score\": 4, \"reason\": \"이유 한 줄\"},\n"
    "  \"answer_relevance\":  {\"score\": 5, \"reason\": \"이유 한 줄\"},\n"
    "  \"context_relevance\": {\"score\": 3, \"reason\": \"이유 한 줄\"}\n"
    "}"
)
